#!/usr/bin/env bash

set -e

host=$(env | grep WAIT_TCP_ADDR | cut -d = -f 2)
port=$(env | grep WAIT_TCP_PORT | cut -d = -f 2)

echo -n "waiting for TCP connection to $host:$port..."

while ! nc -w 1 $host $port 2>/dev/null
do
  echo -n .
  sleep 5
done

./opt/portal/bin/htrc-portal -Dconfig.file=conf/application.conf -Dlogger.file=conf/logger.xml
