//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.07 at 10:27:11 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://registry.htrc.i3.illinois.edu/entities/file", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.illinois.i3.htrc.registry.entities.file;
